WIP - Dump the rancher pod logs before killing rancher.

diff --git a/.github/workflows/scripts/integration-test-ci b/.github/workflows/scripts/integration-test-ci
--- a/.github/workflows/scripts/integration-test-ci
+++ b/.github/workflows/scripts/integration-test-ci
@@ -35,33 +35,7 @@ webhook_deployed() {
 try --waitmsg "Waiting for webhook to be deployed (2)" webhook_deployed
 echo "Webhook deployed"
 
-# Shut down the core rancher part, but leave the rest of the rancher environment running
-set -e
-echo "Shutting down core rancher"
-kubectl scale deploy rancher -n cattle-system --replicas=0
-kubectl wait pods -l app=rancher --for=delete -n cattle-system
-
-echo "Uploading new webhook image"
-
-# Install the webhook chart we just built.
-upgrade_rancher_webhook() {
-   helm upgrade rancher-webhook ./dist/artifacts/rancher-webhook-${HELM_CHART_VERSION}.tgz -n cattle-system \
-    --wait --timeout=120s --set image.repository="${IMAGE_REPO}" --set image.tag="${IMAGE_TAG}" --reuse-values --debug
-}
-
-set +e
-
-try --max 3 --delay 2 --waitmsg "Upgrading Webhook" --failmsg "Failed to upgrade webhook" upgrade_rancher_webhook
-
-x=$(kubectl get pods -n cattle-system -l app=rancher-webhook | grep -v -e Running -e NAME | awk '{print $1}')
-if [ -n "$x" ] ; then
-  echo "Logs for failed rancher-webhook $x ":
-  kubectl get pods -n cattle-system -l app=rancher-webhook
-  kubectl get pod "$x" -n cattle-system
-  kubectl logs pod/"$x" -n cattle-system
-  kubectl describe pod/"$x" -n cattle-system
-  try --max 4 --failmsg "Couldn't helm upgrade rancher-webhook" upgrade_rancher_webhook
-fi
+echo "What rke-machine things do we have?"
 
 echo "XXX Temporary: what rke-machine-config resources do we have?"
 kubectl api-resources | head -n 1
@@ -93,6 +67,34 @@ for pod in $(kubectl get pods -n cattle-system -l app=rancher -o jsonpath='{.ite
     kubectl logs pod/$pod -n cattle-system | grep -C 10 rke-machine -n
 done
 echo "XXX Done dumping stuff"
+
+# Shut down the core rancher part, but leave the rest of the rancher environment running
+set -e
+echo "Shutting down core rancher"
+kubectl scale deploy rancher -n cattle-system --replicas=0
+kubectl wait pods -l app=rancher --for=delete -n cattle-system
+
+echo "Uploading new webhook image"
+
+# Install the webhook chart we just built.
+upgrade_rancher_webhook() {
+   helm upgrade rancher-webhook ./dist/artifacts/rancher-webhook-${HELM_CHART_VERSION}.tgz -n cattle-system \
+    --wait --timeout=120s --set image.repository="${IMAGE_REPO}" --set image.tag="${IMAGE_TAG}" --reuse-values --debug
+}
+
+set +e
+
+try --max 3 --delay 2 --waitmsg "Upgrading Webhook" --failmsg "Failed to upgrade webhook" upgrade_rancher_webhook
+
+x=$(kubectl get pods -n cattle-system -l app=rancher-webhook | grep -v -e Running -e NAME | awk '{print $1}')
+if [ -n "$x" ] ; then
+  echo "Logs for failed rancher-webhook $x ":
+  kubectl get pods -n cattle-system -l app=rancher-webhook
+  kubectl get pod "$x" -n cattle-system
+  kubectl logs pod/"$x" -n cattle-system
+  kubectl describe pod/"$x" -n cattle-system
+  try --max 4 --failmsg "Couldn't helm upgrade rancher-webhook" upgrade_rancher_webhook
+fi
 
 # Done trying things, so reinstate 'set -e'
 set -e
